### ISSUE TITLE
PAth forward

### ISSUE THREAD

**Issue by Philipp-Neubauer** [Adaptive-dynamics/Sizing-fx-of-temperature#1]
1. Active metabolism should scale with w ? Brett says so, seems to hold for tuna.
2. I doubt the activity rule in Killen et al 2010. Tuna were taken as static (anestitised), so if exponent scales with activity, then this clearly biases results. Also, temp scaling is suspect. Def doesn't glue with tuna results i've seen. So, over-all, I'll go with no difference. Seems Ok given flatfish data and herringe etc. they're all very close.
3. Try temp change in exponent. Not convinced, but again, seems plausible.

**Comment by Kenhasteandersen** [comment]
?

Ken
---------------------------------------------------------------------------------------------------------------
Ken H. Andersen, http://ken.haste.dk, twitter: @69kno
Professor in theoretical marine ecology, head of section, and deputy director of Centre for Ocean Life http://www.oceanlifecentre.dk

New online app: Fish community simulator http://oceanlife.dtuaqua.dk/cspectrum.

[cid:image001.jpg@01D09493.A377DFB0]

On 5 Oct 2017, at 08.48, Philipp Neubauer <notifications@github.com<mailto:notifications@github.com>> wrote:


  1.  Active metabolism should scale with w ? Brett says so, seems to hold for tuna.
  2.  I doubt the activity rule in Killen et al 2010. Tuna were taken as static (anestitised), so if exponent scales with activity, then this clearly biases results. Also, temp scaling is suspect. Def doesn't glue with tuna results i've seen. So, over-all, I'll go with no difference. Seems Ok given flatfish data and herringe etc. they're all very close.
  3.  Try temp change in exponent. Not convinced, but again, seems plausible.

**Comment by Philipp-Neubauer** [comment]
@Kenhasteandersen - sorry, a bit cryptic - some quick notes I wrote on the train to remind me what I have left to do tomorrow; trying to finalise parameter values and pin down sensitivities. 

1. Refers to scaling of active metabolism with weight possibly having an exponent near one - so markedly higher than standard metabolism (assumed to be the same as std metabolism at the moment). Seems there's reasonable evidence for that from Salmon and Tuna, not sure beyond that.
2. Not sure I trust the Killen meta-analysis for standard metabolism changes with temperature and life-history (i.e., pelagic vs benthic). Some questionable values/assumptions that make me wonder about bias and extreme values.
3. Some evidence for intra-specific changes of the metabolic scaling exponent with temperature. Kozlovski showed that this alone can introduce temp-size rule, so worth exploring as a sensitivity.

Hope to send you a write-up over the next few days - getting there.
